language: ruby
cache: bundler # caching to speed up dependency installation
rvm:
- 2.5.1
- 2.4.1
- 2.1.0
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up pkg installation
script:
jobs:
  include:
  - stage: build
    script: script/build
  - stage: tests
    script: script/tests
