# language: ruby
# cache: bundler # caching to speed up dependency installation
# rvm:
# - 2.4.5 # TravisCI prebuilt version
# addons:
#   apt:
#     packages:
#     - libcurl4-openssl-dev # required to avoid SSL errors
# env:
#   global:
#   - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

# before_install:
# - chmod +x script/build # verify TravisCI has permission to execute scripts
# - chmod +x script/tests
# jobs:
#   include:
#     - stage: build
#       name: "Running Jeykll build script..."
#       script: script/build

